config/routes.rb
Vmd::Application.routes.draw do
     
  resources :groups do
    
  end

  resources :aco_aros do
    
     member do
      post 'new'
    end
  end

  resources :aros do
   collection do 
      get 'setup_aros'
    end
    
  end
   
  resources :acos do
    collection do 
      get 'setup_acos'
    end
  end

   

  resources :sys_modules do
    
  end

   
   

  resources :agency_departments do
    
  end

  resources :projects do
    
  end

   
  resources :un_contracts do
    member do
      post 'new'
    end
    collection do
      get 'select_project_account'
      get 'reports_for_lta'
      
    end
  end

  

  resources :funds

  

 resources :reports  

   

 resources :supplier_reports do
   collection do
      post 'index'
    end
 end

  resources :consultant_reports do
    collection do
      post 'index'
    end
  end



 resources :ngo_reports do
   collection do
      post 'index'
    end
 end

  

  resources :sp_ratings   

   
  resources :ng_ratings  
 

   resources :cons_ratings do
    
   end

  resources :n_ratings do
  member do 
     post 'new'
   end
   collection do
     get 'select_ngos'
   end  
  end

   

   resources :s_ratings do
   member do 
     post 'new'
   end
   collection do
     get 'select_sups'
   end 
  end
   

  resources :c_ratings do
   member do 
     post 'new'
   end
   
   collection do
     get 'select_cons'
     get 'search_vendor'
     put 'search_vendor'
   end 
  end

   

  resources :recruitments do
    collection do
       get 'export_to_excel'
   end
  end

   

  resources :app_attachments do
    
  end

 
  resources :vac_applications do
   collection do
       get 'export_to_excel'
   end
  end

   

  resources :vacancies do
    collection do
      get 'view'
      get 'adv_search'
      post 'adv_search'
    end
    
  end

   

  resources :e_mails do
    member do
      #get 'new'
      post 'new'
     get 'view'
     end
     collection do
     get 'send_auto_pass'
    end
    
    collection do
      get 'feedback'
    end
    
    
  end

   
  resources :audit_trails , :only => [:show,:index,:destroy]

  resources :system_wide do
        
    collection do 
      get 'metrics'
      post 'collate_for_export'
    end
    
  end

   

 resources :s_certifications do
 end

  resources :s_contracts do
  
  end
  resources :s_technical_documents do
    
  end

   
  resources :s_bank_infos do
    
  end

   
 resources :s_financials do
   
 end

  

  resources :stelephone do
    
  end

  resources :s_contacts do
    
  end

  resources :suppliers do
    collection do 
     get 'export_to_excel'
     get 'notifications'
   end
     
  end

  resources :n_certifications do
    
  end

  resources :n_contracts do
    
  end

 resources :n_technical_documents do 
    
  end
  

   

  resources :n_bank_infos do
    
  end

 
 resources :n_financials do
   
 end

  

resources :n_contacts do
  
end
resources :ntelephones do 
  
end

 

  resources :ngos do
    collection do 
     get 'export_to_excel'
     get 'notifications'
   end
     
  end
 resources :ngo_services do
   
 end

 resources :c_uploads do
    
  end

   

  resources :c_ext_family_in_undps do
     get 'add' , :on => :collection
     get 'remove' , :on => :collection
  end

  resources :c_miscs do
     get 'add' , :on => :collection
     get 'remove' , :on => :collection
  end

   
  resources :c_languages do
   get 'add' , :on => :collection
   get 'remove' , :on => :collection  
  end

   
  resources :c_de_pendents do
     get 'add' , :on => :collection
     get 'remove' , :on => :collection
  end
  
  resources :c_family_in_undps do
     get 'add' , :on => :collection
     get 'remove' , :on => :collection
  end

   

  resources :c_publications do
    get 'add' , :on => :collection
    get 'remove' , :on => :collection
  end
  resources :c_pro_societies do
   get 'add' , :on => :collection
   get 'remove' , :on => :collection 
  end
   
 resources :cundp_certifications do
   get 'add' , :on => :collection
   get 'remove' , :on => :collection
 end
 
 resources :cun_languages do
  get 'add' , :on => :collection
  get 'remove' , :on => :collection 
 end
   

 resources :c_post_qualifications do
    get 'add' , :on => :collection
    get 'remove' , :on => :collection
 end

 resources :c_educations do
      get 'add' , :on => :collection
      get 'remove' , :on => :collection
     end

 resources :c_employment_records do
    get 'add' , :on => :collection
    get 'remove' , :on => :collection
 end

 resources :c_employment_details do 
     
 end
  
 resources :c_references do
    
 end

  

 resources :ctelephones do
   
 end

 resources :c_contact_details do
   
 end
 resources :consultants do
   collection do 
     get 'export_to_excel'
   end
    
 end

 resources :conservices do
    
 end

 resources :conservtypes do
     
 end

 resources :supservices do
    
 end

  resources :supservtypes do 
    
  end

  resources :statuses do
    
  end

  resources :vpas do
   member do
     get 'listed'
   end
   
   end
   
   resources :vsses do
    member do
       get 'listed' 
   end 
   end
  resources :c_certifications do
    
  end
  resources :vendor_types do
    collection do
    get 't_view_mgr'  
    post 'cons_sup_service' 
    get 'vendor_manager'  
    end
     
  end
  
  resource :logins do 
     collection  do 
       get 'view'
       get 'export_to_excel'
       get 'view'
       get 'index'
       get 'show' 
        
      end
   end
  delete 'logins/reset'
 
  match 'logins/:user_id/view' => 'logins#view' 
  match 'audited/:id' => 'logins#show' 
  match 'audited/:id/remove' => 'logins#destroy'  
  get "pages/home"
  get "pages/faq"
  root :to => "pages#home"
  
  resource :dashboards , :only => :index , :via => :get
  resource :usershomes , :only => :usershome , :via => :get
  resource :supplieruser , :only => [:index ,:supplieruser] , :via => :get
  resource :ngouser , :only => [:index ,:ngouser] , :via => :get
 
  resources :undpusers do
    collection do
      get 'confirmation'
      get 'request_confirmation_link'
      post 'request_confirmation_link'
      put 'signup_change_password'
      get 'signup_change_password'
      get 'forgot_password'
      post 'forgot_password'
      get 'report'
      get 'create_vendor'
      get 'create_staff'
      get 'export_to_excel'
      
    end
    member do
      get 'change_password'
      put 'change_password'
      get 'edit_profile'
      put 'edit_profile'
      get 'vendor_select'
      put 'vendor_select'
   end
    
  end
  
  resources :sessions do
    
  end
  match "/dashboard" => "dashboards#index"
  match "/chome" => "usershomes#usershome"
  match "/shome" => "supplieruser#supplieruser"
  match "/nhome" => "ngouser#ngouser"
  match "/faq" => 'pages#faq'
  match "/login" =>'sessions#new'
  match "/logout" =>'sessions#destroy'
  match "/signup" =>'undpusers#new'
  match "/undpusers/confirmation/:uni_id" => 'undpusers#confirmation'
  match "/vpas/listed/:vendor_type_id" => 'vpas#listed'
  match "/vsses/listed/:vendor_type_id/:vpa_id" => 'vsses#listed'
  match "/conservtypes/:undpuser_id/new" => 'conservtypes#new'
  match "/consultants/:undpuser_id/new" => 'consultants#new'
  match '/feedback' => "e_mails#feedback"
  match 'metrics' => 'system_wide#metrics'
end

app/models/c_education.rb
# == Schema Information
#
# Table name: c_educations
#
#  id              :integer          not null, primary key
#  institution     :string(255)
#  place           :string(255)
#  country         :string(255)
#  qualification   :string(255)
#  course_of_study :string(255)
#  study_type      :string(255)
#  consultant_id   :integer
#  attended_from   :string(255)
#  attended_to     :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class CEducation < ActiveRecord::Base
  belongs_to :consultant ,:foreign_key=>:consultant_id 
  attr_accessible :attended_from, :attended_to, :consultant_id, :country, :course_of_study, :institution, :place, :qualification, :study_type
end

app/controllers/c_educations_controller.rb
class CEducationsController < ApplicationController
  before_filter :login_required , :only => ['index','new','create','update','edit','destroy','show']
  before_filter :consultants_only 
  before_filter :check_consultant  ,:except => ['create','add','remove']
  layout :get_user_layout
  
  def add
    #SESSION tRACKING OF FORMS ADDED
    if session[:added_edu_field].nil? 
      session[:added_edu_field] = 1
    else
    session[:added_edu_field]+= 1
    end
    respond_to do |f|
      f.js
    end
  end
  
  def remove
    respond_to do |f|
      f.js
    end
  end
 
  def new
  end

  def index
  end

  def create
    
 if request.post?
   cEducations = []
   params[:c_educations].each do |ce|
   cEducations <<   {
                    :attended_from => ce[:attended_from]["(1i)"] +"-" + ce[:attended_from]["(2i)"] +"-"+ ce[:attended_from]["(3i)"],
                    :attended_to  => ce[:attended_to]["(1i)"] +"-" + ce[:attended_to]["(2i)"] +"-"+ ce[:attended_to]["(3i)"] ,
                    :consultant_id => "#{ce[:consultant_id]}" ,
                    :country => "#{ce[:country]}" ,
                    :course_of_study => "#{ce[:course_of_study]}" ,
                    :institution => "#{ce[:institution]}" ,
                    :place => "#{ce[:place]}" ,
                    :qualification => "#{ce[:qualification]}" ,
                 
                    :study_type => "#{ce[:study_type]}"
                    }
                    end
   session[:c_educations] = nil
   session[:c_educations] = cEducations
   
   c_postqualifications = []

   params[:c_post_qualification].each do |ce|
   c_postqualifications <<   {
                    :attended_from => ce[:attended_from]["(1i)"] +"-" + ce[:attended_from]["(2i)"] +"-"+ ce[:attended_from]["(3i)"],
                    :attended_to  => ce[:attended_to]["(1i)"] +"-" + ce[:attended_to]["(2i)"] +"-"+ ce[:attended_to]["(3i)"] ,
                    :consultant_id => "#{ce[:consultant_id]}" ,
                    :country => "#{ce[:country]}" ,
                    :course_of_study => "#{ce[:course_of_study]}" ,
                    :institution => "#{ce[:institution]}" ,
                    :place => "#{ce[:place]}" ,
                    :qualification => "#{ce[:qualification]}" ,
                 
                    :study_type => "#{ce[:study_type]}"
                    }
          end 
   session[:c_post_qualification] = nil
   session[:c_post_qualification] = c_postqualifications
 

   c_pro_socs = []
   params[:c_pro_society].each do |cpr|
   
          c_pro_socs <<    {
                :consultant_id => "#{cpr[:consultant_id]}" ,
                :details => "#{cpr[:details]}" ,
                :name => "#{cpr[:name]}"
              }
            end
 session[:c_pro_society] = nil
 session[:c_pro_society] = c_pro_socs
 
 
   c_pubs = []
   params[:c_publication].each do |cpr|
   
          c_pubs <<    {
                :consultant_id => "#{cpr[:consultant_id]}" ,
                :details => "#{cpr[:details]}" ,
                :name => "#{cpr[:name]}"
              }
          end
   session[:c_publication] = nil
   session[:c_publication] = c_pubs
 
 

   c_un_lang = []
   params[:cun_language].each do |ce|
  
   c_un_lang << {
                    :attended_from => ce[:attended_from]["(1i)"] +"-" + ce[:attended_from]["(2i)"] +"-"+ ce[:attended_from]["(3i)"],
                    :attended_to  => ce[:attended_to]["(1i)"] +"-" + ce[:attended_to]["(2i)"] +"-"+ ce[:attended_to]["(3i)"] ,
                    :consultant_id => "#{ce[:consultant_id]}" ,
                    :country => "#{ce[:country]}" ,
                    :course_of_study => "#{ce[:course_of_study]}" ,
                    :institution => "#{ce[:institution]}" ,
                    :place => "#{ce[:place]}" ,
                    :qualification => "#{ce[:qualification]}" ,
                 
                    :study_type => "#{ce[:study_type]}"
                    }
  
                end

   session[:cun_language] = nil 
   session[:cun_language] = c_un_lang


 
   cundp_certifications = []
   params[:cundp_certificate].each do |ce|
    
    cundp_certifications << {
                    :attended_from => ce[:attended_from]["(1i)"] +"-" + ce[:attended_from]["(2i)"] +"-"+ ce[:attended_from]["(3i)"],
                    :attended_to  => ce[:attended_to]["(1i)"] +"-" + ce[:attended_to]["(2i)"] +"-"+ ce[:attended_to]["(3i)"] ,
                    :consultant_id => "#{ce[:consultant_id]}" ,
                    :country => "#{ce[:country]}" ,
                    :course_of_study => "#{ce[:course_of_study]}" ,
                    :institution => "#{ce[:institution]}" ,
                    :place => "#{ce[:place]}" ,
                    :qualification => "#{ce[:qualification]}" ,
                 
                    :study_type => "#{ce[:study_type]}"
                    }
            end

   session[:cundp_certificate] = nil
   session[:cundp_certificate] = cundp_certifications

    
    #My Database preparation
   #cEducations
   
  
  cEducations.delete_if {|c| CEducation.count(:conditions=>c) > 0}
  cEducations.delete_if {|c| c[:institution].nil? || c[:institution] == "" }
  
   if cEducations.size > 0
     CEducation.create(cEducations)
   
   end    
  
   
   #c_postqualifications
   c_postqualifications.delete_if {|c| CPostQualification.count(:conditions=>c) > 0}
  c_postqualifications.delete_if {|c| c[:institution].nil? || c[:institution] == ""}
  
   if c_postqualifications.size > 0
     CPostQualification.create(c_postqualifications)
   
   end 
    
    #c_pro_socs
    c_pro_socs.delete_if {|c| CProSociety.count(:conditions=>c) > 0}
  c_pro_socs.delete_if {|c| c[:name].nil? || c[:name]== ""}
  
   if c_pro_socs.size > 0
     CProSociety.create(c_pro_socs)
   
   end
    
    
    
    #c_pubs
    c_pubs.delete_if {|c| CPublication.count(:conditions=>c) > 0}
  c_pubs.delete_if {|c| c[:name].nil? || c[:name]== ""}
  
   if c_pubs.size > 0
     CPublication.create(c_pubs)
   
   end
    
    
    #c_un_lang 
    
     c_un_lang.delete_if {|c| CunLanguage.count(:conditions=>c) > 0}
     c_un_lang.delete_if {|c| c[:institution].nil? }
  
    if c_un_lang.size > 0
     CunLanguage.create(c_un_lang)
   
    end 
  #cundp_certifications
  
   cundp_certifications.delete_if {|c| CundpCertification.count(:conditions=>c) > 0}
  cundp_certifications.delete_if {|c| c[:institution].nil? }
  
   if cundp_certifications.size > 0
     CundpCertification.create(cundp_certifications)
   
   end 
    
    flash[:notice] = "Successfully save Education details."
 
  else
    flash[:error] = "misunderstood request..."    
 end
  respond_to do |f|
    f.js
    
  end
end

  def edit
    @consultant = CEducation.find(:first, :conditions => {:consultant_id => params[:consultant_id],:id =>params[:id]})
    if !@consultant 
      flash[:error] = "invalid request"
      verify_user_section
    end
  end

  def update
    @consultant = CEducation.find(:first, :conditions => {:id =>params[:id]})
    if @consultant.update_attributes params[:c_education]
      flash[:notice] = "Successfully updated"
    else
      flash[:error] = "Unable to update, try again later"
    end
    respond_to do |f|
      f.html {  if identify_vendor.nil? 
            if request.env["HTTP_REFERER"].nil?
                verify_user_section
                return false
                else
                 redirect_to request.env["HTTP_REFERER"]
                 return false
                 end
              else
                redirect_to c_education_path :id => @consultant.id , :consultant_id => @consultant.consultant_id 
              end
                 }
      f.json
      f.js
    end
  end

  def show
    
    if current_user.group_id == 4
      @consultant = Consultant.find_by_undpuser_id(current_user.id,:include => [:c_educations,:c_post_qualifications,:cun_languages,:cundp_certifications,:c_pro_societies,:c_publications])
      
      if @consultant.nil?
        flash[:error] = "Invalid consultant"
        verify_user_section
      end
     else
        @consultant = Consultant.find_by_id(params[:consultant_id],:include => [:c_educations,:c_post_qualifications,:cun_languages,:cundp_certifications,:c_pro_societies,:c_publications])
        if !@consultant || @consultant.nil?
        flash[:error] = "Invalid consultant"
        if request.env["HTTP_REFERER"].nil?
        redirect_to undpusers_url(:type => 'vendors')
        return false
        else
         redirect_to request.env["HTTP_REFERER"]
         return false
      end
     else 
       @user_title = "For #{@consultant.firstname}  #{@consultant.lastname} :: Consultant"
      
      end
    end
  end

  def destroy
    @consultant = CEducation.find(:first, :conditions => {:id =>params[:id]})
    if @consultant.destroy
      flash[:notice] = "successfully deleted institution"
    else
      flash[:error] = "unable to delete institution"
    end
   
     respond_to do |f|
      f.html {  if identify_vendor.nil? 
                  
                  if request.env["HTTP_REFERER"].nil?
                verify_user_section
                return false
                else
                 redirect_to request.env["HTTP_REFERER"]
                 return false
                 end
  
              else
                redirect_to c_education_path :id => @consultant.id , :consultant_id => @consultant.consultant_id 
              end
                 }
      f.json
      f.js
  end
  end
end

app/helpers/c_educations_helper.rb
module CEducationsHelper
end

app/views/c_educations/_new.html.haml
= form_tag c_educations_url , :remote => true  do 
      
     
  <div class="alert alert-block">Give Full Details - NB (*Give Exact Titles Of Degrees In Original Language*)
  %p Degrees claimed in the job application(even if they are not a requirement for the post) must be completed at the time of the application.
  %p Use the <code>Add</code> buttons to add Extra Blocks.
  </div>
  <div class="alert alert-info">List all institutions attended since age 14 and diplomas/degrees or equivalent qualifications obtained (highest education first). 
  Give the exact name of institution and the title of degrees, diplomas, etc. (Please do not translate or equate to other degrees).</div>
  
  
  <div class="row-fluid">
  <div class="sbh">Institution</div>
  <div class="span3" style="margin-left:0;">
  <label>Name of Institution</label>
  = text_field_tag "c_educations[][institution]" , nil ,:class=>'span12'
  
  <label>Qualification</label>
  - options = [["",""],["PhD","PhD"],["M.Sc","M.Sc"] ,["B.Sc","B.Sc"],["OND","OND"],["HND","HND"],["O\'Levels","O\'Levels"],["Primary School Certificate"," Primary School"],["Other","Other"]]
  = select_tag "c_educations[][qualification]" , options_for_select(options) ,:class=>'span12'
  
  <label>To (Month)</label>
  = date_select("c_educations[][attended_to]","" ,{ :discard_day=>true ,:include_blank =>true,:start_year=>Time.now.year - 50,:end_year=>Time.now.year-1 ,:order=>[:month,:year]},{:class=>'span3',:style=>'float:left;margin-left:2px;width:90px;'})
  </div>
  <div class="span3">
  <label>Place</label>
  = text_field_tag "c_educations[][place]" , nil ,:class=>'span12'
  
  <label>Course of Study</label>
  = text_field_tag "c_educations[][course_of_study]" , nil ,:class=>'span12'
   
  <label> In Person or Online/Remote</label>
  - options = [["",""],["In Person","In Person"],["Online","Online/Remote"] ]
  = select_tag "c_educations[][study_type]" , options_for_select(options) ,:class=>'span12'
  </div>
  <!--/span-->
  <div class="span3">
  <label>Country</label>
  = text_field_tag "c_educations[][country]" , nil ,:class=>'span12'
  
  <label>From (Month)</label>
  = date_select("c_educations[][attended_from]","" ,{ :discard_day=>true ,:include_blank =>true,:start_year=>Time.now.year - 50,:end_year=>Time.now.year-1 ,:order=>[:month,:year]},{:class=>'span3',:style=>'float:left;margin-left:2px;width:90px;'})
  = hidden_field_tag "c_educations[][consultant_id]",session[:cid]
  </div><!--/span-->
  
  <div id="addInstitutions"> </div>
  %p
  <div class="nosredna">&nbsp;</div>
  
   
  <div class="pull-right">
  = link_to '<i class="icon-white icon-plus-sign"></i> Add Institute'.html_safe ,add_c_educations_url(:format=>:js), :remote => true,  :class=>"btn btn-success"
  = link_to '<i class="icon-white icon-minus-sign"></i> Remove Institute'.html_safe ,remove_c_educations_url(:format=>:js), :remote => true,  :class=>"btn btn-danger"
  <div class="nosredna">&nbsp;</div>
  
  </div><!--/row-->
  = render 'c_post_qualifications/new'
  
  <div class="pull-right">
  
  = link_to '<i class="icon-white icon-plus-sign"></i> Add Course'.html_safe ,add_c_post_qualifications_url(:format=>:js), :remote => true,  :class=>"btn btn-success"
  = link_to '<i class="icon-white icon-minus-sign"></i> Remove Course'.html_safe ,remove_c_post_qualifications_url(:format=>:js), :remote => true,  :class=>"btn btn-danger"
  <div class="nosredna">&nbsp;</div></div>
  
  = render 'cun_languages/new'
  
  <div class="pull-right">
  
  = link_to '<i class="icon-white icon-plus-sign"></i> Add UN Language'.html_safe ,add_cun_languages_url(:format=>:js), :remote => true,  :class=>"btn btn-success"
  = link_to '<i class="icon-white icon-minus-sign"></i> Remove UN Language'.html_safe ,remove_cun_languages_url(:format=>:js), :remote => true,  :class=>"btn btn-danger"
  <div class="nosredna">&nbsp;</div></div>
  
  = render 'cundp_certifications/new'
  
  <div class="pull-right">
  
  = link_to '<i class="icon-white icon-plus-sign"></i> Add UNDP Certificate'.html_safe ,add_cundp_certifications_url(:format=>:js), :remote => true,  :class=>"btn btn-success"
  = link_to '<i class="icon-white icon-minus-sign"></i> Remove UNDP Certificate'.html_safe ,remove_cundp_certifications_url(:format=>:js), :remote => true,  :class=>"btn btn-danger"
  <div class="nosredna">&nbsp;</div></div>
  
  = render 'c_pro_societies/new'
  
  <div class="pull-right">
  
  = link_to '<i class="icon-white icon-plus-sign"></i> Add Society '.html_safe ,add_c_pro_societies_url(:format=>:js), :remote => true,  :class=>"btn btn-success"
  = link_to '<i class="icon-white icon-minus-sign"></i> Remove Society'.html_safe ,remove_c_pro_societies_url(:format=>:js), :remote => true,  :class=>"btn btn-danger"
  <div class="nosredna">&nbsp;</div></div>
  
  = render 'c_publications/new'
  
  <div class="pull-right">
  
  = link_to '<i class="icon-white icon-plus-sign"></i> Add Publication '.html_safe ,add_c_publications_url(:format=>:js), :remote => true,  :class=>"btn btn-success"
  = link_to '<i class="icon-white icon-minus-sign"></i> Remove Publication'.html_safe ,remove_c_publications_url(:format=>:js), :remote => true,  :class=>"btn btn-danger"
  <div class="nosredna">&nbsp;</div></div>
  
  
  <div class="nosredna">&nbsp;</div>
  = label_tag " "
  <input class="btn btn-primary" type="submit"  value="Save Education" />
  </div></div></div>  

app/views/c_educations/_new_inst.html.haml
.extraEdu
  <div class="nosredna">&nbsp;</div>
  <div class="sbh">Institution</div>
  <div class="span3" style="margin-left:0;">
  <label>Name of Institution</label>
  = text_field_tag "c_educations[][institution]" , nil ,:class=>'span12'
  
  <label>Qualification</label>
  - options = [["",""],["PhD","PhD"],["M.Sc","M.Sc"] ,["B.Sc","B.Sc"],["OND","OND"],["HND","HND"],["O\'Levels","O\'Levels"],["Primary School Certificate"," Primary School"],["Other","Other"]]
  = select_tag "c_educations[][qualification]" , options_for_select(options) ,:class=>'span12'
  
  <label>To (Month)</label>
  = date_select("c_educations[][attended_to]","" ,{ :discard_day=>true ,:include_blank =>true,:start_year=>Time.now.year - 50,:end_year=>Time.now.year-1 ,:order=>[:month,:year]},{:class=>'span3',:style=>'float:left;margin-left:2px;width:90px;'})
  </div>
  <div class="span3">
  <label>Place</label>
  = text_field_tag "c_educations[][place]" , nil ,:class=>'span12'
  
  <label>Course of Study</label>
  = text_field_tag "c_educations[][course_of_study]" , nil ,:class=>'span12'
   
  <label> In Person or Online/Remote</label>
  - options = [["",""],["In Person","In Person"],["Online","Online/Remote"] ]
  = select_tag "c_educations[][study_type]" , options_for_select(options) ,:class=>'span12'
  </div>
  <!--/span-->
  <div class="span3">
  <label>Country</label>
  = text_field_tag "c_educations[][country]" , nil ,:class=>'span12'
  
  <label>From (Month)</label>
  = date_select("c_educations[][attended_from]","" ,{ :discard_day=>true ,:include_blank =>true,:start_year=>Time.now.year - 50,:end_year=>Time.now.year-1 ,:order=>[:month,:year]},{:class=>'span3',:style=>'float:left;margin-left:2px;width:90px;'})
  = hidden_field_tag "c_educations[][consultant_id]",session[:cid]
  </div><!--/span-->

app/views/c_educations/add.js.erb
$('#addInstitutions').append('<%= j render("new_inst") %>');
$('.datepicker').datepicker({changeMonth: true,changeYear: true}); 
 

 

app/views/c_educations/create.html.erb
<h1>CEducations#create</h1>
<p>Find me in app/views/c_educations/create.html.erb</p>

app/views/c_educations/create.js.haml
- if flash[:notice].nil?
  alert("#{flash[:error]}") ;
- else
  alert("#{flash[:notice]}") ;

app/views/c_educations/destroy.html.erb
<h1>CEducations#destroy</h1>
<p>Find me in app/views/c_educations/destroy.html.erb</p>

app/views/c_educations/index.html.erb
<h1>CEducations#index</h1>
<p>Find me in app/views/c_educations/index.html.erb</p>

app/views/c_educations/new.html.erb
<h1>CEducations#new</h1>
<p>Find me in app/views/c_educations/new.html.erb</p>

app/views/c_educations/remove.js.erb
no_of_extras = $('div[class*=extraEdu]').length ;
if(no_of_extras !=0){
$('div[class*=extraEdu]:last').remove();
}
else
{
alert("No Extra Institution was added");	
}
$('.datepicker').datepicker({changeMonth: true,changeYear: true}); 

app/views/c_educations/update.html.erb
<h1>CEducations#update</h1>
<p>Find me in app/views/c_educations/update.html.erb</p>