config/routes.rb
Vmd::Application.routes.draw do
     
  resources :groups do
    
  end

  resources :aco_aros do
    
     member do
      post 'new'
    end
  end

  resources :aros do
   collection do 
      get 'setup_aros'
    end
    
  end
   
  resources :acos do
    collection do 
      get 'setup_acos'
    end
  end

   

  resources :sys_modules do
    
  end

   
   

  resources :agency_departments do
    
  end

  resources :projects do
    
  end

   
  resources :un_contracts do
    member do
      post 'new'
    end
    collection do
      get 'select_project_account'
      get 'reports_for_lta'
      
    end
  end

  

  resources :funds

  

 resources :reports  

   

 resources :supplier_reports do
   collection do
      post 'index'
    end
 end

  resources :consultant_reports do
    collection do
      post 'index'
    end
  end



 resources :ngo_reports do
   collection do
      post 'index'
    end
 end

  

  resources :sp_ratings   

   
  resources :ng_ratings  
 

   resources :cons_ratings do
    
   end

  resources :n_ratings do
  member do 
     post 'new'
   end
   collection do
     get 'select_ngos'
   end  
  end

   

   resources :s_ratings do
   member do 
     post 'new'
   end
   collection do
     get 'select_sups'
   end 
  end
   

  resources :c_ratings do
   member do 
     post 'new'
   end
   
   collection do
     get 'select_cons'
     get 'search_vendor'
     put 'search_vendor'
   end 
  end

   

  resources :recruitments do
    collection do
       get 'export_to_excel'
   end
  end

   

  resources :app_attachments do
    
  end

 
  resources :vac_applications do
   collection do
       get 'export_to_excel'
   end
  end

   

  resources :vacancies do
    collection do
      get 'view'
      get 'adv_search'
      post 'adv_search'
    end
    
  end

   

  resources :e_mails do
    member do
      #get 'new'
      post 'new'
     get 'view'
     end
     collection do
     get 'send_auto_pass'
    end
    
    collection do
      get 'feedback'
    end
    
    
  end

   
  resources :audit_trails , :only => [:show,:index,:destroy]

  resources :system_wide do
        
    collection do 
      get 'metrics'
      post 'collate_for_export'
    end
    
  end

   

 resources :s_certifications do
 end

  resources :s_contracts do
  
  end
  resources :s_technical_documents do
    
  end

   
  resources :s_bank_infos do
    
  end

   
 resources :s_financials do
   
 end

  

  resources :stelephone do
    
  end

  resources :s_contacts do
    
  end

  resources :suppliers do
    collection do 
     get 'export_to_excel'
     get 'notifications'
   end
     
  end

  resources :n_certifications do
    
  end

  resources :n_contracts do
    
  end

 resources :n_technical_documents do 
    
  end
  

   

  resources :n_bank_infos do
    
  end

 
 resources :n_financials do
   
 end

  

resources :n_contacts do
  
end
resources :ntelephones do 
  
end

 

  resources :ngos do
    collection do 
     get 'export_to_excel'
     get 'notifications'
   end
     
  end
 resources :ngo_services do
   
 end

 resources :c_uploads do
    
  end

   

  resources :c_ext_family_in_undps do
     get 'add' , :on => :collection
     get 'remove' , :on => :collection
  end

  resources :c_miscs do
     get 'add' , :on => :collection
     get 'remove' , :on => :collection
  end

   
  resources :c_languages do
   get 'add' , :on => :collection
   get 'remove' , :on => :collection  
  end

   
  resources :c_de_pendents do
     get 'add' , :on => :collection
     get 'remove' , :on => :collection
  end
  
  resources :c_family_in_undps do
     get 'add' , :on => :collection
     get 'remove' , :on => :collection
  end

   

  resources :c_publications do
    get 'add' , :on => :collection
    get 'remove' , :on => :collection
  end
  resources :c_pro_societies do
   get 'add' , :on => :collection
   get 'remove' , :on => :collection 
  end
   
 resources :cundp_certifications do
   get 'add' , :on => :collection
   get 'remove' , :on => :collection
 end
 
 resources :cun_languages do
  get 'add' , :on => :collection
  get 'remove' , :on => :collection 
 end
   

 resources :c_post_qualifications do
    get 'add' , :on => :collection
    get 'remove' , :on => :collection
 end

 resources :c_educations do
      get 'add' , :on => :collection
      get 'remove' , :on => :collection
     end

 resources :c_employment_records do
    get 'add' , :on => :collection
    get 'remove' , :on => :collection
 end

 resources :c_employment_details do 
     
 end
  
 resources :c_references do
    
 end

  

 resources :ctelephones do
   
 end

 resources :c_contact_details do
   
 end
 resources :consultants do
   collection do 
     get 'export_to_excel'
   end
    
 end

 resources :conservices do
    
 end

 resources :conservtypes do
     
 end

 resources :supservices do
    
 end

  resources :supservtypes do 
    
  end

  resources :statuses do
    
  end

  resources :vpas do
   member do
     get 'listed'
   end
   
   end
   
   resources :vsses do
    member do
       get 'listed' 
   end 
   end
  resources :c_certifications do
    
  end
  resources :vendor_types do
    collection do
    get 't_view_mgr'  
    post 'cons_sup_service' 
    get 'vendor_manager'  
    end
     
  end
  
  resource :logins do 
     collection  do 
       get 'view'
       get 'export_to_excel'
       get 'view'
       get 'index'
       get 'show' 
        
      end
   end
  delete 'logins/reset'
 
  match 'logins/:user_id/view' => 'logins#view' 
  match 'audited/:id' => 'logins#show' 
  match 'audited/:id/remove' => 'logins#destroy'  
  get "pages/home"
  get "pages/faq"
  root :to => "pages#home"
  
  resource :dashboards , :only => :index , :via => :get
  resource :usershomes , :only => :usershome , :via => :get
  resource :supplieruser , :only => [:index ,:supplieruser] , :via => :get
  resource :ngouser , :only => [:index ,:ngouser] , :via => :get
 
  resources :undpusers do
    collection do
      get 'confirmation'
      get 'request_confirmation_link'
      post 'request_confirmation_link'
      put 'signup_change_password'
      get 'signup_change_password'
      get 'forgot_password'
      post 'forgot_password'
      get 'report'
      get 'create_vendor'
      get 'create_staff'
      get 'export_to_excel'
      
    end
    member do
      get 'change_password'
      put 'change_password'
      get 'edit_profile'
      put 'edit_profile'
      get 'vendor_select'
      put 'vendor_select'
   end
    
  end
  
  resources :sessions do
    
  end
  match "/dashboard" => "dashboards#index"
  match "/chome" => "usershomes#usershome"
  match "/shome" => "supplieruser#supplieruser"
  match "/nhome" => "ngouser#ngouser"
  match "/faq" => 'pages#faq'
  match "/login" =>'sessions#new'
  match "/logout" =>'sessions#destroy'
  match "/signup" =>'undpusers#new'
  match "/undpusers/confirmation/:uni_id" => 'undpusers#confirmation'
  match "/vpas/listed/:vendor_type_id" => 'vpas#listed'
  match "/vsses/listed/:vendor_type_id/:vpa_id" => 'vsses#listed'
  match "/conservtypes/:undpuser_id/new" => 'conservtypes#new'
  match "/consultants/:undpuser_id/new" => 'consultants#new'
  match '/feedback' => "e_mails#feedback"
  match 'metrics' => 'system_wide#metrics'
end

app/models/c_ext_family_in_undp.rb
# == Schema Information
#
# Table name: c_ext_family_in_undps
#
#  id            :integer          not null, primary key
#  name          :string(255)
#  relationship  :string(255)
#  name_of_unit  :string(255)
#  duty_station  :string(255)
#  consultant_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class CExtFamilyInUndp < ActiveRecord::Base
   belongs_to :consultant ,:foreign_key=>:consultant_id 

  attr_accessible :consultant_id, :duty_station, :name, :name_of_unit, :relationship
end

app/controllers/c_ext_family_in_undps_controller.rb
class CExtFamilyInUndpsController < ApplicationController
  
  before_filter :login_required , :only => ['index','new','create','update','edit','destroy','show']
  before_filter :consultants_only 
  before_filter :check_consultant  ,:except => ['create','add','remove']
 
  layout :get_user_layout
  def new
  end

  def index
  end

  def create
  end
  
  def edit
    @consultant =CExtFamilyInUndp.find(:first, :conditions => {:consultant_id => params[:consultant_id],:id =>params[:id]})
    if !@consultant 
      flash[:error] = "invalid request"
      verify_user_section
    end
  end

  def update
    @consultant = CExtFamilyInUndp.find(:first, :conditions => {:id =>params[:id]})
    if @consultant.update_attributes params[:c_ext_family_in_undp]
      flash[:notice] = "Successfully updated"
    else
      flash[:error] = "Unable to update, try again later"
    end
    respond_to do |f|
      f.html {  if identify_vendor.nil? 
          if request.env["HTTP_REFERER"].nil?
                verify_user_section
                return false
                else
                 redirect_to request.env["HTTP_REFERER"]
                 return false
                 end
              else
                redirect_to c_misc_path :id => @consultant.id , :consultant_id => @consultant.consultant_id 
              end
                 }
      f.json
      f.js
    end
  end


 def destroy
    @consultant = CExtFamilyInUndp.find(:first, :conditions => {:id =>params[:id]})
    if @consultant.destroy
      flash[:notice] = "successfully deleted!"
    else
      flash[:error] = "unable to delete!"
    end
   
     respond_to do |f|
      f.html {  if identify_vendor.nil? 
        if request.env["HTTP_REFERER"].nil?
                verify_user_section
                return false
                else
                 redirect_to request.env["HTTP_REFERER"]
                 return false
                 end
              else
                redirect_to c_misc_path :id => @consultant.id , :consultant_id => @consultant.consultant_id 
              end
                 }
      f.json
      f.js
  end
  end


  def show
  end
end

app/helpers/c_ext_family_in_undps_helper.rb
module CExtFamilyInUndpsHelper
end

app/views/c_ext_family_in_undps/_new.html.haml
%table{:class => 'fnrd datatable',:id => "addExt"}
  %caption <h5>If Yes, Enter</h5>                  
  %tr 
    %td Name  
    %td Relationship 
    %td Name of Organization
    %td Duty Station 
  %tr
    %td= text_field_tag "c_ext_family_in_undp[][name]" ,nil 
    %td= text_field_tag "c_ext_family_in_undp[][relationship]" ,nil  
    %td= text_field_tag "c_ext_family_in_undp[]name_of_unit]" ,nil 
    %td
      = text_field_tag "c_ext_family_in_undp[]duty_station]" ,nil 
      = hidden_field_tag "c_ext_family_in_undp[]consultant_id]" ,session[:cid]
<div class="nosredna">&nbsp;</div>
<div class="pull-right">
= link_to '<i class="icon-white icon-plus-sign"></i> Add extended'.html_safe, add_c_ext_family_in_undps_url(:format=>:js) ,:remote=>true ,:class=>"btn btn-success" 
= link_to '<i class="icon-white icon-minus-sign"></i> Remove extended'.html_safe, remove_c_ext_family_in_undps_url(:format=>:js) ,:remote=>true ,:class=>"btn btn-danger" 
</div>
<div class="nosredna">&nbsp;</div>

app/views/c_ext_family_in_undps/_new_ext.html.haml
%tr{:class=>'extraExt'}
  %td= text_field_tag "c_ext_family_in_undp[][name]" ,nil 
  %td= text_field_tag "c_ext_family_in_undp[][relationship]" ,nil 
  %td= text_field_tag "c_ext_family_in_undp[]name_of_unit]" ,nil 
  %td
    = text_field_tag "c_ext_family_in_undp[]duty_station]" ,nil 
    = hidden_field_tag "c_ext_family_in_undp[]consultant_id]" ,session[:cid]

app/views/c_ext_family_in_undps/add.js.erb
$('#addExt').append('<%= j render("new_ext") %>');
$('.datepicker').datepicker({changeMonth: true,changeYear: true}); 
 

 

app/views/c_ext_family_in_undps/create.html.erb
<h1>CExtFamilyInUndps#create</h1>
<p>Find me in app/views/c_ext_family_in_undps/create.html.erb</p>

app/views/c_ext_family_in_undps/destroy.html.erb
<h1>CExtFamilyInUndps#destroy</h1>
<p>Find me in app/views/c_ext_family_in_undps/destroy.html.erb</p>

app/views/c_ext_family_in_undps/edit.html.haml
%table{:class => 'fnrd datatable',:id => "addFamily"}
                  
  %tr 
    %td Name  
    %td Relationship 
    %td Name of Organization
    %td Duty Station
    %td Action
  = form_for @consultant do    |f|
    %tr
      %td= f.text_field "name"  
      %td= f.text_field "relationship"  
      %td= f.text_field "name_of_unit"  
      %td
        = f.text_field "duty_station" 
        = f.hidden_field "consultant_id"
      %td <input type="submit" class="btn btn-primary" value="update" />
     
    

app/views/c_ext_family_in_undps/index.html.erb
<h1>CExtFamilyInUndps#index</h1>
<p>Find me in app/views/c_ext_family_in_undps/index.html.erb</p>

app/views/c_ext_family_in_undps/new.html.erb
<h1>CExtFamilyInUndps#new</h1>
<p>Find me in app/views/c_ext_family_in_undps/new.html.erb</p>

app/views/c_ext_family_in_undps/remove.js.erb
no_of_extras = $('tr[class*=extraExt]').length ;
if(no_of_extras !=0){
$('tr[class*=extraExt]:last').remove();
}
else
{
alert("No Extra extended family member block was added!");	
}
$('.datepicker').datepicker({changeMonth: true,changeYear: true}); 

app/views/c_ext_family_in_undps/show.html.erb
<h1>CExtFamilyInUndps#show</h1>
<p>Find me in app/views/c_ext_family_in_undps/show.html.erb</p>

app/views/c_ext_family_in_undps/update.html.erb
<h1>CExtFamilyInUndps#update</h1>
<p>Find me in app/views/c_ext_family_in_undps/update.html.erb</p>